name: Publish to Nexus

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test
      run: mvn clean test
      env:
        BTC_NODE_HOST: ${{ secrets.BTC_NODE_HOST }}
        BTC_NODE_PORT: ${{ secrets.BTC_NODE_PORT }}
        BTC_NODE_RPC_PASSWORD: ${{ secrets.BTC_NODE_RPC_PASSWORD }}
        BTC_NODE_RPC_USER: ${{ secrets.BTC_NODE_RPC_USER }}
    - name: Package
      run: mvn package -Dmaven.test.skip=true
    - name: Release
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        maven_args: -Dmaven.test.skip=true
